services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -d postgres -U postgres']
            interval: 1s
            timeout: 10s
            retries: 50
    adminer:
        image: adminer
        depends_on:
            db:
                condition: service_healthy
    backend:
        image: jeynox/staging_back
        command: sh -c "npm run build && npm run start:prod"
        expose:
            - 5000
        environment:
            - NODE_ENV=production
            - SERVER_PORT=5000
            - JWT_SECRET_KEY=/run/env/jwt_secret_key
        depends_on:
            - db
    frontend:
        image: jeynox/staging_front
        command: sh -c "npm run build"
        volumes:
            - web-front-build:/app/build
        environment:
        - NODE_ENV=production  
    storage-api:
        image: jeynox/staging_storage
        command: sh -c "npm run build && npm run start:prod"
        environment:
        - NODE_ENV=production  

    api_gateway:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - web-front-build:/web-front-build
            - ./logs:/var/log/nginx
        depends_on:
            backend:
                condition: service_healthy
            frontend:
                condition: service_healthy
        ports:
            - 7007:80
volumes:
  web-front-build:

secrets:
    JWT_SECRET_KEY:
        file: ./backend/.env