FROM node:lts-alpine

RUN apk --no-cache add curl

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm i

COPY . .

COPY tsconfig.json tsconfig.json

RUN npm run build

COPY dist dist

CMD npm run start:prod