FROM node:lts-alpine

RUN apk --no-cache add curl

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm config set registry https://registry.npmjs.org/ && \
    for i in 1 2 3; do \
    npm ci && break || { \
    echo "npm install failed, attempt $i/3. Retrying in 30 seconds..." && \
    sleep 30; \
    } \
    done
COPY . .

COPY tsconfig.json tsconfig.json

RUN npm run build

CMD ["npm", "run", "start:prod"]