name: CI Pipeline

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: node:lts-alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker --version

      - name: Build Docker container
        run: |
          docker-compose up --build
        continue-on-error: false

      - name: Run Tests
        run: pytest

      - name: Stop Docker
        run: docker-compose down