name: CI Pipeline

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          touch .env

      - name: Set up Docker
        run: |
          docker --version

      - name: Build Docker container
        run: |
          docker compose up --build  -d
        continue-on-error: false

      - name: Wait for containers to be ready
        run: |
          docker-compose exec frontend curl --fail http://localhost:5173 || exit 1
          docker-compose exec backend curl --fail http://localhost:4000 || exit 1

      - name: Check containers status
        run: |
          docker-compose ps

      - name: Stop API Gateway
        run: |
          docker-compose stop api_gateway

      - name: Stop Docker
        run: docker-compose down